import { MedicalCase } from '@/types';

export const mockCases: MedicalCase[] = [
  {
    id: '1',
    title: 'Chronic Lower Back Pain Follow-up',
    specialty: 'Orthopedics',
    doctorName: 'Dr. Sarah Mitchell',
    visitDate: '2026-04-08',
    summary: 'Discussed ongoing lower back pain management. Doctor recommended physical therapy 3x per week and prescribed anti-inflammatory medication. MRI results showed mild disc herniation at L4-L5.',
    symptoms: ['Lower back pain', 'Numbness in left leg', 'Morning stiffness'],
    createdAt: '2026-04-08T14:30:00Z',
    updatedAt: '2026-04-08T14:30:00Z',
    documentsCount: 3,
    hasVoiceNote: true,
  },
  {
    id: '2',
    title: 'Annual Cardiology Checkup',
    specialty: 'Cardiology',
    doctorName: 'Dr. James Patel',
    visitDate: '2026-03-22',
    summary: 'Routine cardiac evaluation. ECG results were normal. Blood pressure slightly elevated at 135/85. Recommended dietary changes and stress management techniques.',
    symptoms: ['Occasional chest tightness', 'Mild shortness of breath'],
    createdAt: '2026-03-22T10:00:00Z',
    updatedAt: '2026-03-25T09:15:00Z',
    documentsCount: 5,
    hasVoiceNote: false,
  },
  {
    id: '3',
    title: 'Diabetes Management Consultation',
    specialty: 'Endocrinology',
    doctorName: 'Dr. Linda Chen',
    visitDate: '2026-04-01',
    summary: 'HbA1c levels reviewed at 7.2%. Doctor adjusted insulin dosage and provided dietary plan. Next follow-up in 3 months to reassess glucose control.',
    symptoms: ['Fatigue', 'Frequent urination', 'Blurred vision'],
    createdAt: '2026-04-01T11:45:00Z',
    updatedAt: '2026-04-01T11:45:00Z',
    documentsCount: 2,
    hasVoiceNote: true,
  },
];

export const specialties = [
  'Cardiology',
  'Dermatology',
  'Endocrinology',
  'Gastroenterology',
  'General Practice',
  'Neurology',
  'Oncology',
  'Orthopedics',
  'Pediatrics',
  'Psychiatry',
  'Pulmonology',
  'Rheumatology',
  'Urology',
];
